# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Core phylosim model
#' @export
callModel <- function(x, y, dispersal, runs, specRate, negativeDens, positiveDens, env, neutral, mort, mortStrength, repro, dispersalCutoff, nDensCutoff, pDensCutoff, seed, envStrength, nDDStrength, pDDStrength, fission, redQueen, redQueenStrength, protracted, airmatR, soilmatR, prunePhylogeny, envNicheWidth, nDDNicheWidth, pDDNicheWidth) {
    .Call(`_PhyloSim_callModel`, x, y, dispersal, runs, specRate, negativeDens, positiveDens, env, neutral, mort, mortStrength, repro, dispersalCutoff, nDensCutoff, pDensCutoff, seed, envStrength, nDDStrength, pDDStrength, fission, redQueen, redQueenStrength, protracted, airmatR, soilmatR, prunePhylogeny, envNicheWidth, nDDNicheWidth, pDDNicheWidth)
}

