// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// callModel
List callModel(int x, int y, int dispersal, IntegerVector runs, double specRate, bool dens, bool env, bool neutral, bool mort, int mortStrength, bool repro, int dispersalCutoff, int densityCutoff, int seed, double envStrength, double compStrength, int fission, double redQueen, double redQueenStrength, int protracted, NumericVector airmatR, NumericVector soilmatR, bool prunePhylogeny);
RcppExport SEXP _PhyloSim_callModel(SEXP xSEXP, SEXP ySEXP, SEXP dispersalSEXP, SEXP runsSEXP, SEXP specRateSEXP, SEXP densSEXP, SEXP envSEXP, SEXP neutralSEXP, SEXP mortSEXP, SEXP mortStrengthSEXP, SEXP reproSEXP, SEXP dispersalCutoffSEXP, SEXP densityCutoffSEXP, SEXP seedSEXP, SEXP envStrengthSEXP, SEXP compStrengthSEXP, SEXP fissionSEXP, SEXP redQueenSEXP, SEXP redQueenStrengthSEXP, SEXP protractedSEXP, SEXP airmatRSEXP, SEXP soilmatRSEXP, SEXP prunePhylogenySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type dispersal(dispersalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< double >::type specRate(specRateSEXP);
    Rcpp::traits::input_parameter< bool >::type dens(densSEXP);
    Rcpp::traits::input_parameter< bool >::type env(envSEXP);
    Rcpp::traits::input_parameter< bool >::type neutral(neutralSEXP);
    Rcpp::traits::input_parameter< bool >::type mort(mortSEXP);
    Rcpp::traits::input_parameter< int >::type mortStrength(mortStrengthSEXP);
    Rcpp::traits::input_parameter< bool >::type repro(reproSEXP);
    Rcpp::traits::input_parameter< int >::type dispersalCutoff(dispersalCutoffSEXP);
    Rcpp::traits::input_parameter< int >::type densityCutoff(densityCutoffSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type envStrength(envStrengthSEXP);
    Rcpp::traits::input_parameter< double >::type compStrength(compStrengthSEXP);
    Rcpp::traits::input_parameter< int >::type fission(fissionSEXP);
    Rcpp::traits::input_parameter< double >::type redQueen(redQueenSEXP);
    Rcpp::traits::input_parameter< double >::type redQueenStrength(redQueenStrengthSEXP);
    Rcpp::traits::input_parameter< int >::type protracted(protractedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type airmatR(airmatRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type soilmatR(soilmatRSEXP);
    Rcpp::traits::input_parameter< bool >::type prunePhylogeny(prunePhylogenySEXP);
    rcpp_result_gen = Rcpp::wrap(callModel(x, y, dispersal, runs, specRate, dens, env, neutral, mort, mortStrength, repro, dispersalCutoff, densityCutoff, seed, envStrength, compStrength, fission, redQueen, redQueenStrength, protracted, airmatR, soilmatR, prunePhylogeny));
    return rcpp_result_gen;
END_RCPP
}
